### ISSUE TITLE
Can't build following instructions

### ISSUE THREAD

**Issue by Woodwell** [GoogleCloudPlatform/solutions-cloud-adventure-sample-backend-java#1]
[Disclaimer: I'm an android/eclipse relative newbie, and my java is considerably dated, so be gentle :-).  If this is not exactly the right forum (eg there's a public mailing list for questions like these), please point me in the right direction.]

I've downloaded both of the zips and am trying to follow instructions, but I can't get the app built.  The nub of the issue is that the client library generation step does not generate the classes that the app is expecting - instead it generates classes in com.appspot.my_app, which of course means the app does not build.

It's a new install of eclipse (via the adt package) on a Mac.

I'm sure this isn't a bug :-) but perhaps a doc clarification.

**Comment by Woodwell** [comment]
More detail: the generated endpoint-libs directory doesn't look correct.  In particular, the readme.html file references a jar file that does not exist :-(.

**Comment by scaevola** [comment]
There are tons of build tools around and this is  google's solution for sample projects?! : Download code, create new project copy files from there and hell ya!
